/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanEntryRouteImport } from './routes/scan-entry'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AddressRouteImport } from './routes/address'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrdersStatusRouteImport } from './routes/orders.$status'
import { Route as OrderIdRouteImport } from './routes/order.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanEntryRoute = ScanEntryRouteImport.update({
  id: '/scan-entry',
  path: '/scan-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersStatusRoute = OrdersStatusRouteImport.update({
  id: '/orders/$status',
  path: '/orders/$status',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/scan-entry': typeof ScanEntryRoute
  '/settings': typeof SettingsRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/$status': typeof OrdersStatusRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/scan-entry': typeof ScanEntryRoute
  '/settings': typeof SettingsRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/$status': typeof OrdersStatusRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/scan-entry': typeof ScanEntryRoute
  '/settings': typeof SettingsRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/$status': typeof OrdersStatusRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/discover'
    | '/favorites'
    | '/home'
    | '/membership'
    | '/profile'
    | '/scan-entry'
    | '/settings'
    | '/order/$id'
    | '/orders/$status'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/discover'
    | '/favorites'
    | '/home'
    | '/membership'
    | '/profile'
    | '/scan-entry'
    | '/settings'
    | '/order/$id'
    | '/orders/$status'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/address'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/discover'
    | '/favorites'
    | '/home'
    | '/membership'
    | '/profile'
    | '/scan-entry'
    | '/settings'
    | '/order/$id'
    | '/orders/$status'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressRoute: typeof AddressRoute
  CartRoute: typeof CartRoute
  CategoryRoute: typeof CategoryRoute
  CheckoutRoute: typeof CheckoutRoute
  DiscoverRoute: typeof DiscoverRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  MembershipRoute: typeof MembershipRoute
  ProfileRoute: typeof ProfileRoute
  ScanEntryRoute: typeof ScanEntryRoute
  SettingsRoute: typeof SettingsRoute
  OrderIdRoute: typeof OrderIdRoute
  OrdersStatusRoute: typeof OrdersStatusRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-entry': {
      id: '/scan-entry'
      path: '/scan-entry'
      fullPath: '/scan-entry'
      preLoaderRoute: typeof ScanEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address': {
      id: '/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$status': {
      id: '/orders/$status'
      path: '/orders/$status'
      fullPath: '/orders/$status'
      preLoaderRoute: typeof OrdersStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRoute: AddressRoute,
  CartRoute: CartRoute,
  CategoryRoute: CategoryRoute,
  CheckoutRoute: CheckoutRoute,
  DiscoverRoute: DiscoverRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  MembershipRoute: MembershipRoute,
  ProfileRoute: ProfileRoute,
  ScanEntryRoute: ScanEntryRoute,
  SettingsRoute: SettingsRoute,
  OrderIdRoute: OrderIdRoute,
  OrdersStatusRoute: OrdersStatusRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
